name: Deploy Flutter App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.2

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/ClientIRL-keystore

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=../app/ClientIRL-keystore" >> android/key.properties

      - name: Increment Build Number
        run: |
          VERSION_CODE_LINE=$(grep "versionCode =" android/app/build.gradle.kts)
          VERSION_CODE=$(echo $VERSION_CODE_LINE | grep -o "[0-9]\+")
          NEW_VERSION_CODE=$((VERSION_CODE + 1))
          echo "Updating versionCode to $NEW_VERSION_CODE"
          sed -i "s/versionCode = .*/versionCode = $NEW_VERSION_CODE/" android/app/build.gradle.kts
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add android/app/build.gradle.kts
          git commit -m "chore: bump versionCode to $NEW_VERSION_CODE [skip ci]"
          git push origin HEAD:main

      - name: Build App Bundle
        run: flutter build appbundle --flavor prod --release

      - name: Upload to Google Play Closed Testing
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: com.trackittoo.climbirl
          releaseFiles: build/app/outputs/bundle/prodRelease/app-prod-release.aab
          track: alpha
          status: completed
          whatsNewDirectory: distribution/whatsnew
